### ISSUE TITLE
Google Nest Mini no IP or Port found

### ISSUE THREAD

**Issue by DurgNomis-drol** [leikoilja/glocaltokens#28] opened 2021-02-16 16:10 UTC
**Describe the bug**

Does not find an IP or Port for Google Nest Mini 

(Igonere my TV)
`2021-02-16 17:07:36 DEBUG (SyncWorker_1) [custom_components.ha-glocaltokens] [{'device_name': 'Simons TV', 'local_auth_token': 'devicetoken', 'google_device': {'ip': None, 'port': None}}, {'device_name': 'Køkken', 'local_auth_token': device-token', 'google_device': {'ip': None, 'port': None}}]`

**Expected behavior**
IP and Port not None

**Comment by DurgNomis-drol** [comment] 2021-02-16 16:23
Is it possible to use a wildcard for testing? As away to find not support devices?

**Comment by leikoilja** [comment] 2021-02-17 05:25
From what I can see in the `scanner`, `Nest Mini` should be supported (https://github.com/leikoilja/glocaltokens/blob/master/glocaltokens/scanner.py#L11), I am wondering if it might be something with your unicode characters in the name of the device (`Køkken`) that hinders it from being discovered.

I am currently away from my setup where i have a bunch of different Google devices (Google Home mini, Nest mini and Nest Audio). I will be back in a little more than a week, so it's only then I'll be able to test it with them. 

We should ask @ArnyminerZ, if he is aware of wildcard support for zeroconf discovery.

**Comment by DurgNomis-drol** [comment] 2021-02-17 08:58
I just checked by changing the name and it gives the same result. Do you know where he got the names from in the list?

No hurry, i will tinker with and see if I get any where

**Comment by ArnyminerZ** [comment] 2021-02-17 11:07
I have a Google Nest Mini available at home, so I will do some testing, but I believe it was getting detected.

**Comment by DurgNomis-drol** [comment] 2021-02-17 11:16
It does not find an IP for mine, where do you find the name of the device? Do you have a script i can use to test with?

**Comment by ArnyminerZ** [comment] 2021-02-17 11:36
This should show all the devices in your network.
```python3
from glocaltokens.scanner import discover_devices

print(discover_devices())
```

**Comment by DurgNomis-drol** [comment] 2021-02-17 12:10
I get the error `TypeError: discover_devices() missing 1 required positional argument: 'models_list'`

**Comment by DurgNomis-drol** [comment] 2021-02-17 12:13
Fixed it.

I get this from running:
`from glocaltokens.scanner import discover_devices

print(discover_devices(models_list=[]))`

Returns:
`[<glocaltokens.scanner.GoogleDevice object at 0xb6174990>]`

**Comment by ArnyminerZ** [comment] 2021-02-17 12:23
Yeah, that's correct, now you can serialize the results with something like:
```python3
from glocaltokens.scanner import discover_devices

devices = discover_devices(models_list=[])
for device in devices:
    print("{")
    print("name:" + str(name))
    print("ip:" + str(ip))
    print("port:" + str(port))
    print("model:" + str(model))
    print("}")
```

Haven't tested this one, but should work.

**Comment by DurgNomis-drol** [comment] 2021-02-17 12:38
For me it returns with this error
`{
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    print("name:" + str(name))
NameError: name 'name' is not defined
`

**Comment by DurgNomis-drol** [comment] 2021-02-17 12:51
Something is wrong in the way glocaltokens convert the data retrieved by discover_devices(). I can find and retrieve all the information with that, but glocaltokens v2 does not handle it correctly. Thus when it returns json both ip and port is none.

**Comment by ArnyminerZ** [comment] 2021-02-17 13:02
Have you checked that the display name retrieved from `discover_devices` is the same as the one in `get_google_devices`?

**Comment by DurgNomis-drol** [comment] 2021-02-17 13:03
Its the same

**Comment by ArnyminerZ** [comment] 2021-02-17 13:14
Will do some more testing, not sure why it doesn't work... Right now `discover_devices` is not working on my PC, but it's my computer's issue, because in the server it works. So when I have some free time will see what's wrong. I will assign this issue to me.

**Comment by DurgNomis-drol** [comment] 2021-02-17 13:24
When you test, remember to test against my fork. It have been updated with the patch to make it work with glocaltokens v2 
[Here](https://github.com/DurgNomis-drol/ha-glocaltokens)

If there is any thing i can do, let me know :smile:

**Comment by leikoilja** [comment] 2021-02-17 15:35
Yay, awesome collaboration, guys! Thanks a lot for taking care of it, @ArnyminerZ 💥

**Comment by DurgNomis-drol** [comment] 2021-02-18 16:27
It seems to be a problem with HA. #27 even if it returns a warning it seems that HA blocks zeroconf. [Issue here](https://github.com/leikoilja/ha-glocaltokens/issues/36) Because when i run my script manually it works great. A big thumbs up to @ArnyminerZ  for the great job. But in HA it returns `ip=None` and `port=None`.

**Comment by leikoilja** [comment] 2021-02-18 18:25
Sweet! Closing this issue here and if the problem is related to HomeAssistant, let's move it to `ha-glocaltokens` repo.

**Closed by leikoilja** 2021-02-18 18:25 UTC
Labels: bug
